package types

func builtinPopulatedTable() map[string]Type {
	return map[string]Type{
		"argv":                       &Array{StringType},
		"print_int":                  &Fun{UnitType, []Type{IntType}},
		"print_bool":                 &Fun{UnitType, []Type{BoolType}},
		"print_float":                &Fun{UnitType, []Type{FloatType}},
		"print_str":                  &Fun{UnitType, []Type{StringType}},
		"println_int":                &Fun{UnitType, []Type{IntType}},
		"println_bool":               &Fun{UnitType, []Type{BoolType}},
		"println_float":              &Fun{UnitType, []Type{FloatType}},
		"println_str":                &Fun{UnitType, []Type{StringType}},
		"float_to_int":               &Fun{IntType, []Type{FloatType}},
		"int_to_float":               &Fun{FloatType, []Type{IntType}},
		"str_length":                 &Fun{IntType, []Type{StringType}},
		"__str_equal":                &Fun{BoolType, []Type{StringType, StringType}},
		"str_concat":                 &Fun{StringType, []Type{StringType, StringType}},
		"str_sub":                    &Fun{StringType, []Type{StringType, IntType, IntType}},
		"int_to_str":                 &Fun{StringType, []Type{IntType}},
		"float_to_str":               &Fun{StringType, []Type{FloatType}},
		"str_to_int":                 &Fun{IntType, []Type{StringType}},
		"str_to_float":               &Fun{FloatType, []Type{StringType}},
		"get_line":                   &Fun{StringType, []Type{UnitType}},
		"get_char":                   &Fun{StringType, []Type{UnitType}},
		"to_char_code":               &Fun{IntType, []Type{StringType}},
		"from_char_code":             &Fun{StringType, []Type{IntType}},
		"bit_and":                    &Fun{IntType, []Type{IntType, IntType}},
		"bit_or":                     &Fun{IntType, []Type{IntType, IntType}},
		"bit_xor":                    &Fun{IntType, []Type{IntType, IntType}},
		"bit_rsft":                   &Fun{IntType, []Type{IntType, IntType}},
		"bit_lsft":                   &Fun{IntType, []Type{IntType, IntType}},
		"bit_inv":                    &Fun{IntType, []Type{IntType}},
		"time_now":                   &Fun{IntType, []Type{UnitType}},
		"read_file":                  &Fun{&Option{StringType}, []Type{StringType}},
		"write_file":                 &Fun{BoolType, []Type{StringType, StringType}},
		"do_garbage_collection":      &Fun{UnitType, []Type{UnitType}},
		"enable_garbage_collection":  &Fun{UnitType, []Type{UnitType}},
		"disable_garbage_collection": &Fun{UnitType, []Type{UnitType}},
	}
}
